// Generated by reimpl/gen_regions.py -- do not edit.
// Region index for each of the 121 grid cells, recovered from puzzle.gds.
// Rows top to bottom, columns left to right:
//   IIIIICCHGGA
//   IIKIICHHGGA
//   IIKCCCCHHGA
//   IIKCJJJAHHA
//   KIKCJAAAAAA
//   KKKCJJJAEEE
//   CCCCCCJAEBB
//   CDDDJJJAEBB
//   CDDFAAAAEBB
//   CCDFFAAAEEE
//   CDDFAAAAAAA

`default_nettype none

module region_map (
    input  wire [3:0] row,
    input  wire [3:0] col,
    output reg  [3:0] rgn
);
    always @* case ({row, col})
        8'h00: rgn = 4'd8;  // ( 0, 0) region I
        8'h01: rgn = 4'd8;  // ( 0, 1) region I
        8'h02: rgn = 4'd8;  // ( 0, 2) region I
        8'h03: rgn = 4'd8;  // ( 0, 3) region I
        8'h04: rgn = 4'd8;  // ( 0, 4) region I
        8'h05: rgn = 4'd2;  // ( 0, 5) region C
        8'h06: rgn = 4'd2;  // ( 0, 6) region C
        8'h07: rgn = 4'd7;  // ( 0, 7) region H
        8'h08: rgn = 4'd6;  // ( 0, 8) region G
        8'h09: rgn = 4'd6;  // ( 0, 9) region G
        8'h0A: rgn = 4'd0;  // ( 0,10) region A
        8'h10: rgn = 4'd8;  // ( 1, 0) region I
        8'h11: rgn = 4'd8;  // ( 1, 1) region I
        8'h12: rgn = 4'd10;  // ( 1, 2) region K
        8'h13: rgn = 4'd8;  // ( 1, 3) region I
        8'h14: rgn = 4'd8;  // ( 1, 4) region I
        8'h15: rgn = 4'd2;  // ( 1, 5) region C
        8'h16: rgn = 4'd7;  // ( 1, 6) region H
        8'h17: rgn = 4'd7;  // ( 1, 7) region H
        8'h18: rgn = 4'd6;  // ( 1, 8) region G
        8'h19: rgn = 4'd6;  // ( 1, 9) region G
        8'h1A: rgn = 4'd0;  // ( 1,10) region A
        8'h20: rgn = 4'd8;  // ( 2, 0) region I
        8'h21: rgn = 4'd8;  // ( 2, 1) region I
        8'h22: rgn = 4'd10;  // ( 2, 2) region K
        8'h23: rgn = 4'd2;  // ( 2, 3) region C
        8'h24: rgn = 4'd2;  // ( 2, 4) region C
        8'h25: rgn = 4'd2;  // ( 2, 5) region C
        8'h26: rgn = 4'd2;  // ( 2, 6) region C
        8'h27: rgn = 4'd7;  // ( 2, 7) region H
        8'h28: rgn = 4'd7;  // ( 2, 8) region H
        8'h29: rgn = 4'd6;  // ( 2, 9) region G
        8'h2A: rgn = 4'd0;  // ( 2,10) region A
        8'h30: rgn = 4'd8;  // ( 3, 0) region I
        8'h31: rgn = 4'd8;  // ( 3, 1) region I
        8'h32: rgn = 4'd10;  // ( 3, 2) region K
        8'h33: rgn = 4'd2;  // ( 3, 3) region C
        8'h34: rgn = 4'd9;  // ( 3, 4) region J
        8'h35: rgn = 4'd9;  // ( 3, 5) region J
        8'h36: rgn = 4'd9;  // ( 3, 6) region J
        8'h37: rgn = 4'd0;  // ( 3, 7) region A
        8'h38: rgn = 4'd7;  // ( 3, 8) region H
        8'h39: rgn = 4'd7;  // ( 3, 9) region H
        8'h3A: rgn = 4'd0;  // ( 3,10) region A
        8'h40: rgn = 4'd10;  // ( 4, 0) region K
        8'h41: rgn = 4'd8;  // ( 4, 1) region I
        8'h42: rgn = 4'd10;  // ( 4, 2) region K
        8'h43: rgn = 4'd2;  // ( 4, 3) region C
        8'h44: rgn = 4'd9;  // ( 4, 4) region J
        8'h45: rgn = 4'd0;  // ( 4, 5) region A
        8'h46: rgn = 4'd0;  // ( 4, 6) region A
        8'h47: rgn = 4'd0;  // ( 4, 7) region A
        8'h48: rgn = 4'd0;  // ( 4, 8) region A
        8'h49: rgn = 4'd0;  // ( 4, 9) region A
        8'h4A: rgn = 4'd0;  // ( 4,10) region A
        8'h50: rgn = 4'd10;  // ( 5, 0) region K
        8'h51: rgn = 4'd10;  // ( 5, 1) region K
        8'h52: rgn = 4'd10;  // ( 5, 2) region K
        8'h53: rgn = 4'd2;  // ( 5, 3) region C
        8'h54: rgn = 4'd9;  // ( 5, 4) region J
        8'h55: rgn = 4'd9;  // ( 5, 5) region J
        8'h56: rgn = 4'd9;  // ( 5, 6) region J
        8'h57: rgn = 4'd0;  // ( 5, 7) region A
        8'h58: rgn = 4'd4;  // ( 5, 8) region E
        8'h59: rgn = 4'd4;  // ( 5, 9) region E
        8'h5A: rgn = 4'd4;  // ( 5,10) region E
        8'h60: rgn = 4'd2;  // ( 6, 0) region C
        8'h61: rgn = 4'd2;  // ( 6, 1) region C
        8'h62: rgn = 4'd2;  // ( 6, 2) region C
        8'h63: rgn = 4'd2;  // ( 6, 3) region C
        8'h64: rgn = 4'd2;  // ( 6, 4) region C
        8'h65: rgn = 4'd2;  // ( 6, 5) region C
        8'h66: rgn = 4'd9;  // ( 6, 6) region J
        8'h67: rgn = 4'd0;  // ( 6, 7) region A
        8'h68: rgn = 4'd4;  // ( 6, 8) region E
        8'h69: rgn = 4'd1;  // ( 6, 9) region B
        8'h6A: rgn = 4'd1;  // ( 6,10) region B
        8'h70: rgn = 4'd2;  // ( 7, 0) region C
        8'h71: rgn = 4'd3;  // ( 7, 1) region D
        8'h72: rgn = 4'd3;  // ( 7, 2) region D
        8'h73: rgn = 4'd3;  // ( 7, 3) region D
        8'h74: rgn = 4'd9;  // ( 7, 4) region J
        8'h75: rgn = 4'd9;  // ( 7, 5) region J
        8'h76: rgn = 4'd9;  // ( 7, 6) region J
        8'h77: rgn = 4'd0;  // ( 7, 7) region A
        8'h78: rgn = 4'd4;  // ( 7, 8) region E
        8'h79: rgn = 4'd1;  // ( 7, 9) region B
        8'h7A: rgn = 4'd1;  // ( 7,10) region B
        8'h80: rgn = 4'd2;  // ( 8, 0) region C
        8'h81: rgn = 4'd3;  // ( 8, 1) region D
        8'h82: rgn = 4'd3;  // ( 8, 2) region D
        8'h83: rgn = 4'd5;  // ( 8, 3) region F
        8'h84: rgn = 4'd0;  // ( 8, 4) region A
        8'h85: rgn = 4'd0;  // ( 8, 5) region A
        8'h86: rgn = 4'd0;  // ( 8, 6) region A
        8'h87: rgn = 4'd0;  // ( 8, 7) region A
        8'h88: rgn = 4'd4;  // ( 8, 8) region E
        8'h89: rgn = 4'd1;  // ( 8, 9) region B
        8'h8A: rgn = 4'd1;  // ( 8,10) region B
        8'h90: rgn = 4'd2;  // ( 9, 0) region C
        8'h91: rgn = 4'd2;  // ( 9, 1) region C
        8'h92: rgn = 4'd3;  // ( 9, 2) region D
        8'h93: rgn = 4'd5;  // ( 9, 3) region F
        8'h94: rgn = 4'd5;  // ( 9, 4) region F
        8'h95: rgn = 4'd0;  // ( 9, 5) region A
        8'h96: rgn = 4'd0;  // ( 9, 6) region A
        8'h97: rgn = 4'd0;  // ( 9, 7) region A
        8'h98: rgn = 4'd4;  // ( 9, 8) region E
        8'h99: rgn = 4'd4;  // ( 9, 9) region E
        8'h9A: rgn = 4'd4;  // ( 9,10) region E
        8'hA0: rgn = 4'd2;  // (10, 0) region C
        8'hA1: rgn = 4'd3;  // (10, 1) region D
        8'hA2: rgn = 4'd3;  // (10, 2) region D
        8'hA3: rgn = 4'd5;  // (10, 3) region F
        8'hA4: rgn = 4'd0;  // (10, 4) region A
        8'hA5: rgn = 4'd0;  // (10, 5) region A
        8'hA6: rgn = 4'd0;  // (10, 6) region A
        8'hA7: rgn = 4'd0;  // (10, 7) region A
        8'hA8: rgn = 4'd0;  // (10, 8) region A
        8'hA9: rgn = 4'd0;  // (10, 9) region A
        8'hAA: rgn = 4'd0;  // (10,10) region A
        default: rgn = 4'd0;
    endcase
endmodule

`default_nettype wire
