"""Emit the region lookup table as Verilog, from the map recovered from the netlist.

Provenance: tools/starbattle.REGIONS was read directly off puzzle.gds by asking, for
each of the 121 grid cells, which region accumulator flop a star there perturbs. This
script only transcribes it, so the RTL cannot disagree with the measurement.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from tools.starbattle import REGIONS, W

letters = sorted({ch for row in REGIONS for ch in row})
idx = {ch: i for i, ch in enumerate(letters)}
out = [
    "// Generated by reimpl/gen_regions.py -- do not edit.",
    "// Region index for each of the 121 grid cells, recovered from puzzle.gds.",
    "// Rows top to bottom, columns left to right:",
]
out += [f"//   {r}" for r in REGIONS]
out.append("")
out.append("`default_nettype none")
out.append("")
out.append("module region_map (")
out.append("    input  wire [3:0] row,")
out.append("    input  wire [3:0] col,")
out.append("    output reg  [3:0] rgn")
out.append(");")
out.append("    always @* case ({row, col})")
for r in range(W):
    for c in range(W):
        out.append(f"        8'h{(r << 4) | c:02X}: rgn = 4'd{idx[REGIONS[r][c]]};"
                   f"  // ({r:2d},{c:2d}) region {REGIONS[r][c]}")
out.append("        default: rgn = 4'd0;")
out.append("    endcase")
out.append("endmodule")
out.append("")
out.append("`default_nettype wire")
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "rtl", "region_map.v")
open(path, "w").write("\n".join(out) + "\n")
print(f"wrote {path}: {W*W} entries, {len(letters)} regions")
